### ISSUE TITLE
SIEM - Linux logs data sources

### ISSUE THREAD

**Issue by 4sm-ops** [devops-ru/awesome-devsecops_ru#1]
# Новый контент
https://docs.google.com/spreadsheets/d/1ccXuv4KZ1ndNFKwNuXpTgvgMgvQ16joUI408v232a9I/
* Небольшое описание - ``
Linux logs data sources (for Information Security purposes). Links to appropriate Splunk Apps are available as well.
* Ссылка на материал - ``

**Comment by Nklya** [comment]
Thanks!
