### ISSUE TITLE
DevSecCon Videos

### ISSUE THREAD

**Issue by vizdrag** [devops-ru/awesome-devsecops_ru#3]
# DevSec conference

* Небольшое описание -

* Ссылка на материал -
https://www.youtube.com/watch?v=6IRz6F5Y4Zo&list=PLZN13UbkqPfWNy4WUd0UuWYCss69n7A10
https://www.youtube.com/watch?v=u0tUea0Cbdc&list=PLZN13UbkqPfUmt4IZmoTWcbou-oxUivoV

**Comment by Nklya** [comment]
Thanks for your contribution!
