### ISSUE TITLE
Awesome cheat sheets on the Development methodology

### ISSUE THREAD

**Issue by h0c0b** [devops-ru/awesome-devsecops_ru#4]
# Modern Software Development Methodologies explained simple

* Небольшое описание -
Not all security guys are proficient in software development methodologies. Most of their proposals work fine for the Waterfall, however we are talking DevSecOps here. Below are the greatest cheat sheets I've ever seen on modern software development methodology that will bootstrap your old fashioned InfoSecs.

* Ссылка на материал -
https://www.developmentthatpays.com/cheatsheets

**Comment by Nklya** [comment]
Thanks for your contribution!
