### ISSUE TITLE
AWS Security Making the Shift from DevOps to Practical DevSecOps

### ISSUE THREAD

**Issue by vizdrag** [devops-ru/awesome-devsecops_ru#5]
# AWS Security Making the Shift from DevOps to Practical DevSecOps

* Небольшое описание - Предлагаю добавить подразделы для безопасности тех или иных облачных платформ, в виде разделов:
Digital Ocean
AWS
Google Cloud
etc.

* Ссылка на материал -https://www.youtube.com/watch?v=BAsLEsEVThM

**Comment by Nklya** [comment]
Спасибо за ссылку и предложение, добавил.
Сорян за задержку 🤗
