### ISSUE TITLE
Безопасность Docker

### ISSUE THREAD

**Issue by shad0wrunner** [devops-ru/awesome-devsecops_ru#6]
# Новый контент
Приветствую!
Предлагаю добавить ссылки на три статьи про безопасность докера и репозиторий со скриптами для интеграции проверок безопасности. Извините, что в одном issue сразу всё - оно по одной теме :)

* Небольшое описание:
В статьях последовательно раскрывается область Docker, которую стоит анализировать с точки зрения безопасности, рассматриваются утилиты, которые покрывают отдельные участки этой области и приводятся примеры (+скрипты и контейнеры) как можно внедрить утилиты проверки безопасности в CI/CD процесс.

* Ссылка на материал:
https://swordfishsecurity.ru/blog/docker_security
https://swordfishsecurity.ru/blog/obzor-utilit-bezopasnosti-docker
https://swordfishsecurity.ru/docker-security-scanning-examples
И репозиторий с описанными инструкциями
https://github.com/Swordfish-Security/docker_cicd/

**Comment by Nklya** [comment]
Привет.
Спасибо за статьи, добавил!
